name: OSCAL CI/CD Setup Java

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: 11
      distribution:
        required: false
        type: string
        default: temurin
      uses-dependency-manager:
        required: false
        type: boolean
        default: false
      cache:
        required: false
        type: string
        default: maven
jobs:
  configure-oscal-runtimes-java:
    name: OSCAL CI/CD Setup Java
    runs-on: ubuntu-20.04
    steps:
    - name: Configure Java Runtime (without Dependency Management)
      if: ${{ !inputs.uses-dependency-manager }}
      uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
      id: configuration-without-deps
    - name: Configure Java Runtime (with Dependency Management)
      if: ${{ inputs.uses-dependency-manager }}
      uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
      id: configuration-with-deps