name: Test Reusable Workflows in Repo

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  setup-runtimes-java:
    uses: aj-stein-nist/test-gha-reusable-workflows/.github/workflows/setup-runtime-java.yml@main
  setup-runtimes-python:
    uses: aj-stein-nist/test-gha-reusable-workflows/.github/workflows/setup-runtime-python.yml@main
  setup-runtimes-nodejs:
    uses: aj-stein-nist/test-gha-reusable-workflows/.github/workflows/setup-runtime-nodejs.yml@main
    with:
      node-version-file: .nvmrc