name: Test Reusable Workflows in Repo

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  setup-runtimes-java:
    uses: aj-stein-nist/test-gha-reusable-workflows/.github/workflows/setup-runtime-java.yml@main
    with:
      uses-dependency-manager: true
      cache: maven
